### ISSUE TITLE
Module Boxes do not expand/collapse

### ISSUE THREAD

**Issue by esudalaimadan** [sudar/bulk-move#102]
- Module Boxes do not expand/collapse.
- Unchecking checkboxes in Screen Options do not hide the respective module.
- Unable to drag module boxes.
Please see attached screenshots:
![selection_005](https://user-images.githubusercontent.com/38071735/48328470-19e28e80-e66a-11e8-8e12-ab121348d01d.png)
![selection_006](https://user-images.githubusercontent.com/38071735/48328472-1c44e880-e66a-11e8-869f-16bdb25a3827.png)

**Comment by sudar** [comment]
@esudalaimadan 

Check if you are able to replicate this issue in the latest copy of `dev/2.0.0`

**Comment by sudar** [comment]
Closing this, since this is fixed now.
