### ISSUE TITLE
Screen options show/hide not working

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-move#107]
This issue was identified as part of https://github.com/sudar/bulk-move/issues/104

![screen-options](https://user-images.githubusercontent.com/17510033/56409581-4c3a8c80-6297-11e9-8212-5dfea5bf5175.gif)

Steps to replicate:

- Clone the Git repo
- Execute `composer install`, `npm install` and `grunt`
- Activate the plugin
- Navigate to **Bulk WP** ⟶ **Bulk Move Posts**
- Select **Screen Options** and try toggling the checkboxes.

**Comment by sudar** [comment]
@mariadanieldeepak 

Check if you are able to replicate this issue after running `grunt vendor`.

I am not able to replicate this.

**Comment by mariadanieldeepak** [comment]
@sudar,

`grunt vendor` did the trick. I can confirm that the screen options work as expected.
