### ISSUE TITLE
JS Error: select2 is not a function

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-move#109]
I executed `npm install` && `grunt` after getting the latest from `dev/2.0.0`. Not sure why I'm getting the following error yet. Could you check this?

![image](https://user-images.githubusercontent.com/17510033/56434538-9e5ccb80-62f2-11e9-86bb-a0c9b109fc2c.png)

Apart from **Move Posts By Custom Taxonomy** module, `dev/2.0.0` is good to go.

**Comment by sudar** [comment]
@mariadanieldeepak 

You also need to run `grunt vendor` command.

**Comment by mariadanieldeepak** [comment]
Thanks @sudar, this is resolved now. Hence I'm closing this issue.
