### ISSUE TITLE
Add screenshots

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-move#13]

**Comment by mariadanieldeepak** [comment]
@sudar,

Could you explain what needs to be done here? Screenshots of the all the Bulk Delete Screens?

**Comment by sudar** [comment]
@mariadanieldeepak 

Right now the Bulk Move plugin doesn't have screenshots.

You need to add a couple of screenshots explaining the features of the Bulk Move plugin like how did for Bulk Delete plugin.

**Comment by mariadanieldeepak** [comment]
@sudar,

This will be taken up once we complete https://github.com/sudar/bulk-move/pull/16
So, the new feature is also included in the screenshots.

**Comment by mariadanieldeepak** [comment]
@sudar - If there are no visual changes on Bulk Move menu screens, I can go ahead and take the screenshots.

**Comment by sudar** [comment]
@mariadanieldeepak 

For the `v1.3` release we are not going to change the menu structure.

For the screenshots, let's have some tags. Right now in a couple of screenshots the tag's dropdown is empty. This might confuse users.

I have also added description about the screenshots in README file, so maintain the screenshot number.
