### ISSUE TITLE
Plugin's page inesorably crashes on blog with lots of tags

### ISSUE THREAD

**Issue by DrLightman** [sudar/bulk-move#14]
In the specific, the methods:

::render_move_tag_box
::render_move_category_by_tag_box

Which hold the SELECT html controls to hold ALL the blog tags. In blog's installations with an huge amount of tags, this leads to a catastrophe.

An idea could be to replace the SELECTs with autocompletion input texts, like the one in the Edit Post screen.

**Comment by sudar** [comment]
@DrLightman 

Thanks for reporting this issue. I will look into it to see if auto-completion can be implemented.

**Comment by DrLightman** [comment]
Thanks for the feedback. Meanwhiel I've replaced the two select with two text inputs without autocompletion, so that I've had to put the tag IDs manually, and it worked.
