### ISSUE TITLE
Bulk Move Users between roles

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-move#23]
Plugins already exist for the same function, but consider this - 

https://wordpress.org/support/topic/assigning-users-who-have-no-role/

**Comment by sudar** [comment]
This should be in a new page called 'Bulk Move Users'

In that we should have a module called 'Bulk Move Users by User Role'.

The module should lists the user roles on the left and right side.

Once a role is selected on the left and right side, the users who belong to the user role on the left side should be moved to the user role selected on the right side.

**Comment by mariadanieldeepak** [comment]
@sudar,

Will this be released under `1.4.0` or `2.0`?

**Comment by mariadanieldeepak** [comment]
@sudar,

Is the following menu structure same as the one you expected?

![image](https://user-images.githubusercontent.com/17510033/33240949-f97d728e-d2e4-11e7-9aae-6c268d5e0742.png)

**Comment by sudar** [comment]
@mariadanieldeepak 

> Will this be released under 1.4.0 or 2.0?

This will be part of 2.0.0. You can find it from the milestone.

> Is the following menu structure same as the one you expected?

I was planning to integrate this with Bulk Delete. See #19 

Hold this till I finish #19

**Comment by sudar** [comment]
@mariadanieldeepak 

This is now unblocked for you.

**Comment by sudar** [comment]
We should also add test cases for this.
