### ISSUE TITLE
Do a content audit of the help section

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-move#27]
And update content in help section if needed

**Comment by mariadanieldeepak** [comment]
- https://github.com/sudar/bulk-move/issues/33 Warning should use `notice-warning` class and not `notice-success` class

- https://github.com/sudar/bulk-move/issues/34 Change About Plugin to About Bulk WP

- https://github.com/sudar/bulk-move/issues/35 Update Help section Copy

- #36 Update Help section links

**Comment by mariadanieldeepak** [comment]
@sudar,

I couldn't think of anything other than the points I captured above.

**Comment by sudar** [comment]
Closing this and all items of the review will be handled as part of the sub tickets.
