### ISSUE TITLE
Add tests for 'Move by Custom Taxonomy' metabox

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-move#44]
This needs to be done together with #43

**Comment by mariadanieldeepak** [comment]
@sudar,

I was able to add and run tests for Move Posts by Custom Taxonomy using the default WordPress posts and categories.

Could you please throw some light on 
- how to register new taxonomy, 
- then create custom terms?

@anandB000 - Kindly take a look at the tests written so far as part of this to-do. Once @sudar shares some insights, you may take this up and complete the rest (2 more test cases).

**Comment by sudar** [comment]
@mariadanieldeepak @anandB000 

Refer to 

https://pippinsplugins.com/unit-tests-for-wordpress-plugins-the-factory/
http://richardsweeney.com/testing-integrations/
