### ISSUE TITLE
Add additional test cases to 'Move by Taxonomy' Module

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-move#59]
Do this after #43

**Comment by mariadanieldeepak** [comment]
@sudar,

This was supposed to be assigned to @anandB000. But I completed the test cases to speed things up. I'll transfer tasks to @anandB000 when I find a good chunk.

**Comment by sudar** [comment]
@mariadanieldeepak sure, go ahead.

You may also have to change the base class of the test cases.

**Comment by mariadanieldeepak** [comment]
@anandB000,

Could you write tests for the cases that is explained in the video?

https://bulkwp.slack.com/archives/C030FQZKZ/p1518310026000047
https://bulkwp.slack.com/archives/C030FQZKZ/p1518310058000074

@sudar - Kindly advise if @anandB000 has to wait for #49 to be merged before he starts working on this.

**Comment by sudar** [comment]
@mariadanieldeepak 

Let's get #49 merged. Otherwise it is going to create too much confusion.

**Comment by sudar** [comment]
@anandB000 

You can start working on it now.
