### ISSUE TITLE
Possible low-to-no impact issue

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-move#67]
Shouldn't the following value be https://github.com/sudar/bulk-move/blob/dev/2.0.0/include/Page/Post.php#L63 in the form of https://github.com/sudar/bulk-move/blob/dev/2.0.0/include/Metabox/Base.php#L175

**Comment by sudar** [comment]
@mariadanieldeepak 

Yes you are correct.

`$meta_field = 'metaboxhidden_bulk-wp_page_' . $this->page_slug;`

Should be 

`$meta_field = 'metaboxhidden_toplevel_page_' . $this->page_slug;`
