### ISSUE TITLE
Test Bulk Move modules manually

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-move#79]
Video description: https://bulkwp.slack.com/archives/C030FQZKZ/p1518310607000018

**Comment by anandB000** [comment]
Two failure cases for 1) Move Posts from Tag to Category and 2) Move Posts from Category To Tag when applying Remove them filter.

**Comment by anandB000** [comment]
**1 ) Move Posts from Category To Tag**

**Category** ==

We have tow post named post1 and post_common. And also we have two categories named cat1 and cat_common.  Then post1 is assigned cat1 and cat_common then the post_common is assigned to cat_common.

Finally post1 have cat1 and cat_common and post_common have cat_common.

cat1 = one post
cat_common = two post

**Tag** ==

We have tow post named post1 and post_common. And also we have two tags named tag1 and tag_common.  Then post1 is assigned tag1 and tag_common then the post_common is assigned to tag_common.

Finally post1 have tag1 and tag_common and post_common have tag_common.

tag1 = one post
tag_common = two post

== **Move posts from category to tag** ==

= **Test case 1 move category to tag** [ Filter : Remove them ] =

_Options_

cat_common (2) ==> tag_common (2)

_Result expected_ 

cat1 and cat_common have 0 post, tag1 have 1 post and tag_common have 2 post.

_We get now_

cat_common have 0 post, cat1 have 1 post, tag1 have 0 post and tag_common have 2 post.


**Before**

![cat_before_move_1](https://user-images.githubusercontent.com/22234994/36989138-e0b0b768-20c6-11e8-8e6f-741f14325a39.png)
![cat_before_move_2](https://user-images.githubusercontent.com/22234994/36989139-e1182024-20c6-11e8-8b2c-86ce4df019ac.png)

**After**

![cat_after_move_1](https://user-images.githubusercontent.com/22234994/36989134-e043c82e-20c6-11e8-97c2-1409db0d99d5.png)
![cat_after_move_2](https://user-images.githubusercontent.com/22234994/36989136-e07c53e2-20c6-11e8-84ca-b141275e1289.png)

**Comment by anandB000** [comment]
**2 ) Move Posts from Tag To Category**

tag1 = one post
tag_common = two post

== **Move Posts from Tag To Category** ==

= **Test case 1 move tag to category** [ Filter : Remove them ] =

_Options_

tag_common (2) ==> cat_common (2)

_Result expected _

tag1 and tag_common have 0 post, cat1 have 1 post and cat_common have 2 post.

_We get now_

tag_common have 0 post, tag1 have 1 post, cat1 have 0 post and cat_common have 2 post.
