### ISSUE TITLE
Fix JS issues

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-move#80]
see https://scrutinizer-ci.com/g/sudar/bulk-move/issues/dev/2.0.0/files/assets/js/bulk-move.js?orderField=path&order=asc&honorSelectedPaths=0&issueId=27599311#inspectioncomment-98297358

see https://scrutinizer-ci.com/g/sudar/bulk-move/issues/dev/2.0.0/files/assets/js/bulk-move.js?orderField=path&order=asc&honorSelectedPaths=0&issueId=27774916#inspectioncomment-98297357

**Comment by mariadanieldeepak** [comment]
@sudar,

Both links return a 404.

![image](https://user-images.githubusercontent.com/17510033/36520190-99c7e2f0-17b5-11e8-8aff-d53d5e9718b3.png)

**Comment by sudar** [comment]
@mariadanieldeepak 

You should be able to see the issues at https://scrutinizer-ci.com/g/sudar/bulk-move/issues/dev/2.0.0/files/assets/js/src/bulk-move.js?orderField=path&order=asc&honorSelectedPaths=0

Here is the screenshot of the issue description.

<img width="1118" alt="screenshot 2018-02-22 17 02 52" src="https://user-images.githubusercontent.com/103148/36536244-3c623024-17f2-11e8-9b8d-b542447e5a02.png">
