### ISSUE TITLE
Check and remove commented code

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-move#82]
Any idea why you commented this code?

If it is not relevant anymore then remove the commented code.

see https://scrutinizer-ci.com/g/sudar/bulk-move/issues/dev/2.0.0/files/include/Page/Base.php?orderField=path&order=asc&fileId=include%2FMetabox%2FPosts%2FTagToCategory.php&honorSelectedPaths=0&issueId=27502026#inspectioncomment-97985881

**Comment by mariadanieldeepak** [comment]
@sudar,

> Any idea why you commented this code?

My original intention was to lay the format down as part of inline documentation ;) Now it is clear that my comment failed its purpose. So I'm removing it.
