### ISSUE TITLE
Include missing test cases for Move Posts by Custom Taxonomy

### ISSUE THREAD

**Issue by mariadanieldeepak** [sudar/bulk-move#86]
This issue is a follow-up of https://github.com/sudar/bulk-move/issues/84

Write tests for the following cases.

![image](https://user-images.githubusercontent.com/17510033/36409744-508c01f8-1633-11e8-9450-75059e461a5c.png)

Remove Term with overwrite
Remove Term without overwrite

**Comment by sudar** [comment]
@rajanit2000 

Some documentation about writing Unit tests in WordPress

https://pippinsplugins.com/unit-tests-wordpress-plugins-introduction/
