### ISSUE TITLE
Bulk move of 4,000+ posts halts with "405 Not Allowed"

### ISSUE THREAD

**Issue by skinnedpanda** [sudar/bulk-move#99]
The host is running nginx/1.14.0

This issue might not be the plugin's fault.

It did about 1,300 posts before the error message came first. I was able to continue by refreshing the browser window (F5) and confirm form resubmission. It then stopped multiple times, doing anywhere from 200-500 posts. At one point Wordpress reported that it was unable to contact the database: "Error establishing a database connection". After a few minutes, it again was able to connect.

**Comment by sudar** [comment]
Hello @skinnedpanda,

Looks like your database server is not able to handle the load.

Each post that is getting deleted will generate lot of queries in the DB and when the number of posts that is getting deleted increase, the db server might slow down.

One alternative is to delete the posts in batches, so that your DB server doesn't get loaded.

**Comment by skinnedpanda** [comment]
Yes, you're right. It is working in the background despite the 405 Error. Great plugin. Thank you!

**Comment by sudar** [comment]
Glad to know that our plugin was working even when the db server was under load. Also nice to know that you like our plugin.

In future if you have any questions about our plugin, feel free to reach out to us.

**Comment by skinnedpanda** [comment]
FYI, I later learnt that another plugin, made to share posts on a social media platform (not Jetpack), was the one making problems. It went bananas when it thought that the bulk-move was a bunch of new posts, so it was sharing every single post, no matter how old.

Next time, I will deactivate all other plugins to prevent something like this to happen again.

**Comment by sudar** [comment]
@skinnedpanda 

Thank you very much for giving us this additional detail. We will add a note about social media sharing plugins to our troubleshooting guide.
